platform :ios, "8.0"

# 忽略所有依赖库的警告
inhibit_all_warnings!

use_frameworks!

pod 'CocoaAsyncSocket' # Socket封装

pod 'JDStatusBarNotification' # 状态栏提示

#pod 'Mantle'        # Json模型
pod 'JSONModel'        # Json模型

pod 'PINCache'      # 缓存库

pod 'ReactiveCocoa', '4.0.4-alpha-1' # 响应式编程框架

pod 'IQKeyboardManagerSwift' # 防止键盘遮挡的库

pod 'SnapKit' # Autolayout库